apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: httpd
  name: apache-cluster3
  namespace: simple-app
spec:
  clusterSelector:
    matchLabels:
      clusterid: cluster3