apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: apache-cluster1                           
  namespace: simple-app
  labels:
    name: httpd
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: assets/overlays/cluster1
spec:
  channel:  simple-app/federation
  placement: 
    placementRef: 
      kind: PlacementRule
      name: apache-cluster1
