apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: book-import
  name: book-import
  namespace: simple-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: book-import
  sessionAffinity: None
  type: ClusterIP
